"""add leverage to orders and positions

Revision ID: 0e1f2ead35e1
Revises: b2c3d4e5f6a7
Create Date: 2026-05-30 16:53:14.043152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1f2ead35e1'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('leverage', sa.Integer(), server_default='1', nullable=False))
    op.add_column('positions', sa.Column('leverage', sa.Integer(), server_default='1', nullable=False))
    op.add_column('positions', sa.Column('liquidation_price', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'liquidation_price')
    op.drop_column('positions', 'leverage')
    op.drop_column('orders', 'leverage')
    # ### end Alembic commands ###
